const cssRules = new Set();

// Generated by Selenium IDE
import { Builder, By, Key, until } from 'selenium-webdriver';
import assert from 'assert';

describe('few moves', function() {
    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function() {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function() {
        await driver.quit();
    })
    it('few moves', async function() {
        await driver.get("http://localhost:3000/")
        await driver.manage().window().setRect(1927, 977)
        await driver.findElement(By.css(".row:nth-child(2) > .square:nth-child(4) img")).click()
        await driver.findElement(By.css(".row:nth-child(4) > .highlight")).click()
        await driver.findElement(By.css(".row:nth-child(7) > .square:nth-child(5) img")).click()
        await driver.findElement(By.css(".row:nth-child(5) > .highlight")).click()
        await driver.findElement(By.css(".row:nth-child(2) > .square:nth-child(6) img")).click()
        await driver.findElement(By.css(".row:nth-child(4) > .highlight")).click()
        await driver.findElement(By.css(".row:nth-child(5) img")).click()
        await driver.findElement(By.css(".highlight:nth-child(6) > .chess-piece")).click()
        await driver.findElement(By.css(".row:nth-child(1) > .square:nth-child(3) img")).click()
        await driver.findElement(By.css(".highlight img")).click()

        // Extract and log CSS rules applied to elements
        const elements = await driver.findElements(By.css('*'));
        for (const element of elements) {
            const computedStyle = await element.getCssValue('all');
            console.log(computedStyle);
        }
    })
})